"""Initial migration.

Revision ID: ad0f1815f0fb
Revises: 
Create Date: 2021-03-16 09:51:09.872269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad0f1815f0fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('c',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('reg_num', sa.String(length=120), nullable=True),
    sa.Column('address1', sa.String(length=120), nullable=True),
    sa.Column('city1', sa.String(length=120), nullable=True),
    sa.Column('county1', sa.String(length=120), nullable=True),
    sa.Column('postcode1', sa.String(length=120), nullable=True),
    sa.Column('address2', sa.String(length=120), nullable=True),
    sa.Column('city2', sa.String(length=120), nullable=True),
    sa.Column('county2', sa.String(length=120), nullable=True),
    sa.Column('postcode2', sa.String(length=120), nullable=True),
    sa.Column('address3', sa.String(length=120), nullable=True),
    sa.Column('city3', sa.String(length=120), nullable=True),
    sa.Column('county3', sa.String(length=120), nullable=True),
    sa.Column('postcode3', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.Column('facebook_link', sa.String(length=120), nullable=True),
    sa.Column('linkedin_link', sa.String(length=120), nullable=True),
    sa.Column('website', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('m',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('waste_stream', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('county', sa.String(length=120), nullable=True),
    sa.Column('dimensions', sa.String(length=120), nullable=True),
    sa.Column('condition', sa.String(length=120), nullable=True),
    sa.Column('image_link1', sa.String(length=120), nullable=True),
    sa.Column('image_link2', sa.String(length=120), nullable=True),
    sa.Column('image_link3', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('m')
    op.drop_table('c')
    # ### end Alembic commands ###
